### ISSUE TITLE
Convert blob data from aerospike to spark

### ISSUE THREAD

**Issue by sasi21033** [sasha-polev/aerospark#11]
Hi,

We are saving blob data which is serializable and we want to spilt to bins and records.
Is there away to do so?

Thanks,
Sasi

**Comment by sasi21033** [comment]
Hey Sasha,
Any thoughts about this issue?
Is there away to intercept the transform of aerospike to SQL spark table.
Thanks,
Sasi

**Comment by sasha-polev** [comment]
Hi Sasi

You should just write a spark function and apply to row (using
.map(parseRow) function). Not really specific to connector, will be same
for any connector in Spark.

Thanks
Sasha

**Comment by sasi21033** [comment]
Thanks for the idea, i'll try it now.

**Comment by sasi21033** [comment]
Hi Sasha,
Thanks for the response.
Where should I put such function? I mean when I create temp table with query of "select * from set" then each update/remove occur automatically with RDD, therefore I don't have any control on the data.
Thanks,
Sasi

**Comment by sasha-polev** [comment]
Hi Sasi

I do not understand your flow, to be honest. But you do not need to create
temp tables - spark uses lazy eval of RDDs and does trasformations like
.map() inline.

Thanks
Sasha

**Comment by sasi21033** [comment]
Hi Sasha,

I'll try to explain my flow and the architecture:
I have 2 aerospikes and 2 slaves on machine A.
I have 1 master and 1 JBoss on  machine B..

From the JBoss server I'm running the following code:
 DataFrame dataFrame = sqlCtx.sql("CREATE TEMPORARY TABLE tbl1 USING com.osscube.spark.aerospike.rdd OPTIONS ("host:port, query, useUdfWithoutIndexQuery true");
dataFrame.persist(StorageLevel.MEMORY_ONLY());

And i'm using this sqlContext to do queries on that temporary table. (I found this code on comment that you gave on one of the issues here).

The temporary code works once, because spark update the RDD all the time.

The problem I have is that some of the data saved has Blob in aerospike and I need to pull one parameter from it. E.g. If I want to do filter on name that in the blob then I need to extract it and put it on the table, so it will be easy to access via SQLContext.

Let me know if that make sense or I do stuff on wrong way.

Thanks for your help!
Sasi

**Comment by sasi21033** [comment]
Hello Sasha,
What do you thing about my flow and architecture?
Sasi

**Comment by sasi21033** [comment]
just me make it clear. the content of the blob data is a proprietary object that serialize in a binary format to the aerospike. 
in order to use properties from this object we need to deserialize it back to the original object and map its values to the temporary table.

**Comment by sasha-polev** [comment]
Hi Sasi


I understand. The thing is that DataFrame is special type of RDD, it has
similar but extended behaviour to RDD of type Row, with known schema:
http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.DataFrame

With usual spark RDD you can apply Map( Row => Row ) function  to RDD and
get RDD with different structure of Row (that function should decode binary
value to multiple attributes  so it will produce different number of
columns to original row). Then you will need to apply new schema to RDD
that will give column names to new row, like here:
http://spark.apache.org/docs/latest/sql-programming-guide.html#interoperating-with-rdds


Then you will have new dataframe  with new structure that you can cache in
memory and use as the one you do currently.

BTW, this is not really related to Aerospike, so you can send me email
directly to "Alexander (Sasha) Polev" <sasha@onepointltd.com>.

Thanks
Sasha

**Comment by sasi21033** [comment]
Thanks for your help!
I'll close this ticket and you'll contact you via email!
Thanks again!

Sasi
