### ISSUE TITLE
DataFrame with rows contains empty data when Aerospike has empty table.

### ISSUE THREAD

**Issue by sasi21033** [sasha-polev/aerospark#14]
Hi Sasha,
I found a bug that seems to be from the connector.
1) Aerospike contains empty bin.
2) My driver create new DataFrame using Aerospark connector:
`
SparkContextFunctions scf= new SparkContextFunctions(sparkCtx);
DataFrame df = scf.aeroSInput(aeroSpikeAddress, query, sqlCtx 4);
df.registerTempTable(TableConfiguration.TABLE_NAME);
`
3) Doing df.collect() at the first return empty which OK.
4) Add new row to Aerospike.
5) Verify the new row with aql.
6) Run df.collect() again and you'll get Rows length is > 0, but the content of each row empty.

Looks like the DataFrame doesn't get refresh/sync with Aerospike.

If you run the same scenario when there's data on the Aerospike, then it won't happen.
 Sasi

**Comment by sasha-polev** [comment]
Well, since aerospike does not have schema connector does its best to guess
it when rdd is declared. So one of the main assumptions is that schema of
all records is same.

If you declare it on incomplete row it will not be able to parse data.

In this case best to use aeroinput and declare schema yourself. I can check
later if this approach would work in your scenario.

Thanks
Sasha

**Comment by sasi21033** [comment]
Hi Sasha,
I did the following code and it works. (I don't know about the preforms because DF is much faster.)

`  AerospikeRDD aeroSpikeRdd = scf.aeroInput(aeroSpikeAddress, query, 4);
            StructType schema = DataTypes.createStructType(new StructField[] { DataTypes.createStructField("REG_ORIGIN", DataTypes.StringType, false), //
                    DataTypes.createStructField("field1", DataTypes.StringType, false), //
                    DataTypes.createStructField("fields", DataTypes.StringType, false)});
          df.registerTempTable(TableConfiguration.TABLE_NAME);`

And it fixed the issue/bug.

Thanks,
Sasi

**Comment by sasha-polev** [comment]
Great!

Thanks
Sasha
