### ISSUE TITLE
Select with variable structure

### ISSUE THREAD

**Issue by tivvit** [sasha-polev/aerospark#17]
Hi, 

I tried to create RDD from select with not fixed data structure. I mean that one record contans bin "a" and another "b". When I use `select * from ..` I get only one bin name in the results (because of caching mentioned below) but when I use all bin names `select a,b from ..` i get Exception because Null is coverted to value.

I find out that structure is cached, but even if I commented the caching out the problem is the same.

I am willing to help if this issue is reasonable.

**Comment by sasha-polev** [comment]
Hi Vit

You cant use standard data source approach in your case, as it expects uniform structure. Please look at sample code in issue 14 - it may do what you need.

Thanks
Sasha

**Comment by tivvit** [comment]
Thank you Sasha, I looked at that but I don't get the example.
I get that I have to create the structure by myself, but how should I use `aeroInput` as source and map that to the structure. 

I edited the example as follows:
```scala
val df: DataFrame = sc.aeroSInput("aeros1.dev:3000", "select * from scan.dk", sqlContext, 6)
val aeroSpikeRdd: AerospikeRDD = sc.aeroInput("aeros1.dev:3000", "select * from scan.dk", 4)
val schema: StructType = DataTypes.createStructType(List[StructField](DataTypes.createStructField("REG_ORIGIN", DataTypes.StringType, false)))
df.registerTempTable(TableConfiguration.TABLE_NAME)
```

Thanks for help.

**Comment by sasha-polev** [comment]
Hi Vit

This does not look like a correct code, here is same link I shared before with Sasi: http://spark.apache.org/docs/latest/sql-programming-guide.html#programmatically-specifying-the-schema

aeroInput is simple RDD of type Row, so all you need is to apply your schema.

Thanks
Sasha

**Comment by tivvit** [comment]
Thanks a lot, I solved it.
My data structure is quite bad for that, because I have 2**14 bins (half of aerospike's maximum) because every record takes some space and it is more space efficient to store them in sparse structure with bins hashed to fixed space.
With `aeroInput` it is not possible to load all the bins, but I load them in batches and merge the RDDs. 
I have also discovered that with `aeroInput` it is not possible to use `select * ` because it returns 0 results, but that is probably also ok.

You may close the issue, and thanks again.
