### ISSUE TITLE
Can't build connector

### ISSUE THREAD

**Issue by KaganRoman** [sasha-polev/aerospark#2]
Compiling the aerospark I got this error. Please advise:

[INFO] Compiling 7 source files to /home/dev/aerospark/target/classes at 1428584618789
[ERROR] /home/dev/aerospark/src/main/scala/com/osscube/spark/aerospike/rdd/AerospikeRDD.scala:77: error: overloaded method value setAggregateFunction with alternatives:
[INFO]   (x$1: ClassLoader,x$2: String,x$3: String,x$4: String,x$5: <repeated...>[com.aerospike.client.Value])Unit <and>
[INFO]   (x$1: String,x$2: String,x$3: <repeated...>[com.aerospike.client.Value])Unit
[INFO]  cannot be applied to (String, String, Array[com.aerospike.client.Value], Boolean)
[INFO]       newSt.setAggregateFunction("spark_filters", "multifilter", udfFilters, true)

**Comment by sasha-polev** [comment]
Hi, thanks for reporting this

Yes, POM file references latest version of Aerospike Java driver, which seem have changed method signature.

I will work on upgrade, in a meantime fixing version of the client to 3.0.35 in pom.xml will do the trick:

      <dependency>
        <groupId>com.aerospike</groupId>
        <artifactId>aerospike-client</artifactId>
        <version>3.0.35</version>
      </dependency>

**Comment by KaganRoman** [comment]
Thanks @sasha-polev, it worked like a charm and I successfully compiled the jar !

However, when running an example, it fails when I call to aeroSInput (tried different input strings). Is it because of old version too?

scala> val aero  = sc.aeroSInput("192.168.142.162:3000","select column1,column1,intColumn1 from test.one_million where intColumn1 between -10000000 and 10000000", sqlContext ,6)
java.lang.NoSuchMethodError: com.osscube.spark.aerospike.rdd.SparkContextFunctions.aeroSInput(Ljava/lang/String;Ljava/lang/String;Lorg/apache/spark/sql/SQLContext;I)Lorg/apache/spark/sql/DataFrame;

**Comment by sasha-polev** [comment]
I think this time it is a version of Spark. last time I worked on it there was no DataFrame API. You can see that POM is referencing 1.2.0 version of Spark, and you are probably on 1.3.0

Will try to update the project for Spark 1.3.0 and post here.

Thanks
Sasha

**Comment by sasha-polev** [comment]
I pushed initial changes to support latest Aerospike API and Spark 1.3.0 but did not have time to test it today (will do on weekend). But you can try it on your own :-)

**Comment by KaganRoman** [comment]
Thanks @sasha-polev for so quick response. It works, both of them !!
Have a nice weekend :)
