### ISSUE TITLE
Connect to multiple Aerospike hosts

### ISSUE THREAD

**Issue by sasi2103** [sasha-polev/aerospark#4]
Hi,
Is there away to connect multiple Aerospike hosts?
Is there any constant to tell Spark on which host Aerospike is located?

Thanks,
Sasi

**Comment by sasha-polev** [comment]
Whenever you create Aerospike RDD or temp table (SparkSQL) or dataframe you provide hostname and port of the first node, connector will discover all other nodes in the cluster automatically. 

If you want to connect to another cluster you need to crate another RDD/Dataframe.

There are no constants / environment variable involved, just initial parameter:

CREATE TEMPORARY TABLE aero
USING com.osscube.spark.aerospike.rdd
OPTIONS (initialHost "**192.168.142.162:3000**",
select "select * from test.one_million");


Does this answer your question? 

Thanks
Sasha

**Comment by sasi2103** [comment]
Hi,
Thanks for the fast response.
My topology as the follow:
* Two VMs with Spark workers and two Aerospike.s on the same machine. (192.168.231.15 and 192.168.231.18)
* One Spark master on different machine. (192.168.231.15)
* One java client that connect to the master.

Data:
1. On Aerospike contains 2 rows.
2. Other aerospike contains 1 row.

This is my code:
```java
SparkConf conf = new SparkConf();
conf.setMaster("spark://192.168.231.15:7077");
conf.setAppName("aerospike-test");
SparkContext sparkContext = new SparkContext(conf);
SparkContextFunctions scf = new SparkContextFunctions(sparkContext);
AerospikeRDD aerospikeRDD = scf.aeroInput("192.168.231.18:3000", "select name,name2 from test", 6);
scala.collection.Iterator<Row> iterator = aerospikeRDD.toLocalIterator();
while (iterator.hasNext()) {
 Row row = iterator.next();
System.out.println(row.get(0));
}
```

When I run this code I get results only from 192.168.231.18.
Any idea why?
Thanks,
Sasi

**Comment by sasha-polev** [comment]
Hi Sasi

Are these two Aerospike nodes part of the same cluster?

Thanks
Sasha

**Comment by sasi2103** [comment]
Hi Sasha,

Yes, at least I think :).

```
network {
        service {
                address any
                port 3000
        }
        heartbeat {
                mode mesh
                address 192.168.231.16
                port 3002 # Heartbeat port for this node.
                mesh-seed-address-port 192.168.231.18 3002
                interval 250
                timeout 10
        }

network {
        service {
                address any
                port 3000
        }

        heartbeat {
                mode mesh
                address 192.168.231.18
                port 3002 # Heartbeat port for this node.
                mesh-seed-address-port 192.168.231.16 3002
```

Also when using aql i'm getting the following error:
``` aql> 2015-09-10 15:13:39 WARN AEROSPIKE_ERR_TIMEOUT ```
Only on one node.

Thanks,
Sasi

**Comment by sasha-polev** [comment]
Best way to check and run asinfo command:

[localhost ~]$ asinfo
1 :  node
     BB9F1AC4F290C00
2 :  statistics
     cluster_size=2;....

Thanks
Sasha

**Comment by sasi2103** [comment]
```
2 :  statistics
     cluster_size=2;cluster_key=
````

**Comment by sasha-polev** [comment]
Hmm, looks quite good.

In your case RDD should have 2 partitions with all rows in them.

Can you output:
1) aql -> show sets
2) aerospikeRDD.count (from initial code you sent)

Thanks Sasha

**Comment by sasha-polev** [comment]
Closing this as no response received.
