### ISSUE TITLE
Select key from records return no results found

### ISSUE THREAD

**Issue by thefishermanhacker** [sasha-polev/aerospark#6]
Hi all,

I need to get the key value from sets, so if I do e.g.
select key from ns.set
then I get no results found.

I'm using Aerospark connector.

Is there any way to get it? When I do select * from ns.set I see it under bin key.

Thanks,

**Comment by sasha-polev** [comment]
Hi

DataSet/Dataframe does not contain key in current version. Can see if it is possible to include using some flag. For now you will need to duplicate key in another bin.

Thanks
Sasha
