### ISSUE TITLE
Limit functionality is missing on aeroapark connector.

### ISSUE THREAD

**Issue by thefishermanhacker** [sasha-polev/aerospark#7]
Hi,
Is there away to use `limit` keyword on queries?
If not, is there a feature request?

Thanks,

**Comment by sasha-polev** [comment]
Hi

You can use LIMIT in Spark SQL queries, the iteration will just stop and query will be terminated. Data will never be read from Aerospike into Spark.

AQL (Aerospike SQL) does not use LIMIT clause, so you cant use it when declaring datasource

Hope that helps.

Thanks
Sasha

**Comment by thefishermanhacker** [comment]
Thanks for the response.
So I need to create:
1) application/driver that runs over Spark slave, which run aql queries and stored them in the cache.
2) run Spark SQL on my client which run query against the cached view.

Thanks,

**Comment by sasha-polev** [comment]
Well, not really.

it really depends if you use Spark SQL or pure Spark, but everything is
defined in the driver and then executed by workers. Its just you first
define initial RDD/dataframe with AQL and then can filter it down with SQL
or take N statements. Only required number of rows will be actually read
from Aerospike.

Thanks
Sasha

**Comment by thefishermanhacker** [comment]
Cool, Thanks for your help!
I managed to do so!

Sasi
